service: serveless-project

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  profile: serverlessUser
  region: us-east-1
  environment:
    tableName: ${self:custom.tableName}
    bucketName: ${self:custom.bucketName}
    queueName: ${self:custom.queueName}
  apiGateway:
    shouldStartNameWithService: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
        - s3:*
        - sqs:*
      Resource: '*'
  apiKeys:
    - free:
      - freeApiKey
  usagePlan:
    - free:
        quota:
          limit: 5
          period: DAY
        throttle:
          rateLimit: 5
          burstLimit: 20

plugins:
  - serverless-s3-sync
  - serverless-webpack

package:
  individually: true

custom:
  tableName: player-points
  bucketName: serveless-project-dev-bucket
  queueName: serveless-project-sqs
  s3Sync:
      - bucketName: ${self:custom.bucketName}
        localDir: UploadData

functions:
  getFakeUser:
    handler: lambdas/getFakeUser.handler
    events:
      - http:
          path: get-user/{ID}
          method: GET
          cors: true
          private: true
  getPlayerScore:
    handler: lambdas/getPlayerScore.handler
    events:
      - http:
          path: get-player-score/{ID}
          method: GET
          cors: true
  setPlayerScore:
    handler: lambdas/setPlayerScore.handler
    events:
      - http:
          path: set-player-score
          method: POST
          cors: true
  processFile:
    handler: lambdas/processFile.handler
    events:
      - s3:
          bucket: ${self:custom.bucketName}
          event: s3:ObjectCreated:*
          rules:
            - prefix: files/
            - suffix: .txt
          existing: true
  saveContent:
    handler: lambdas/saveContent.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - MyQueue
              - Arn

resources:
 Resources:
   MyQueue:
     Type: "AWS::SQS::Queue"
     Properties:
       QueueName: ${self:custom.queueName}
   MyS3Bucket:
     Type: AWS::S3::Bucket
     Properties:
       BucketName: ${self:custom.bucketName}
   MyDynamoDBTable:
     Type: AWS::DynamoDB::Table
     Properties:
       TableName: ${self:custom.tableName}
       AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
       KeySchema:
          - AttributeName: ID
            KeyType: HASH
       BillingMode: PAY_PER_REQUEST